### ISSUE TITLE
Airflow DAGs are poorly named and formatted

### ISSUE THREAD

**Issue by harterrt** [mozilla/telemetry-airflow#155]
In a moment of clarity, I realized that the DAGs are defined in python files. We should be using better variable names (e.g. not t1, t2, t3) and should take a look at formatting these definitions better.

For example, in the [main_summary.py DAG](https://github.com/mozilla/telemetry-airflow/blob/master/dags/main_summary.py) `t1` should be renamed to `main_summary`. Then we can say things like: `search_daily_rollups.set_upstream(main_summary)` instead of `t5.set_upstream(t1)`.

**Comment by mreid-moz** [comment]
fixed by #186
