### ISSUE TITLE
Consider passing AWS credential environment variables through via docker-compose

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/telemetry-airflow#178]
Per [this comment](https://github.com/mozilla/telemetry-airflow/pull/176#discussion_r141916807), it may be preferable to specify the AWS credential environment variables to be passed through in the `docker-compose.yml` file rather than only in that one target within the `Makefile`.

In the past, I've relied on the lack of credentials to prevent launching tons of EMR jobs when starting up airflow locally, though in modern times DAGs automatically start up disabled IIUC.

**Comment by acmiyaguchi** [comment]
AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID have been passed in since https://github.com/mozilla/telemetry-airflow/commit/2e4d63e778b8b49cc5193510e4282b8f2e2f9fce.
