### ISSUE TITLE
main_summary.experiments_aggregates_import may overwrite production data in dev

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/telemetry-airflow#310]
https://github.com/mozilla/telemetry-airflow/blob/1d2cc3b82c40b71e18936b45217abd9861fce967/dags/main_summary.py#L155-L157

@robhudson is this job safe to run with a different bucket as a source i.e. `telemetry-test-bucket` on a local airflow instance? Or will it fail because the dev airflow doesn't have the right keys?

**Comment by robhudson** [comment]
I've never tried. If it can access the credentials.json on S3 I would imagine it can work fine.

**Comment by acmiyaguchi** [comment]
I'm double checking that testing the `main_summary` DAG with a subset of data won't overwrite whatever gets sent to test-tube. Do you know what the backfill behavior is like?

**Comment by acmiyaguchi** [comment]
I've disabled this job in dev by effectively making it a no-op.
