### ISSUE TITLE
tab_spinner.py jobs don't appear to be running

### ISSUE THREAD

**Issue by mikeconley** [mozilla/telemetry-airflow#420]
My [dashboard that visualizes the data from the tab_spinner job](https://mikeconley.github.io/bug1310250/) hasn't gotten new data since January 27th. Any idea what's going on?

**Comment by fbertsch** [comment]
The job looks like it's failing because of a serialization error, usually related to pickle. I've opened up https://bugzilla.mozilla.org/show_bug.cgi?id=1525022.
