### ISSUE TITLE
Fix or deprecate EMRSparkOperator

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/telemetry-airflow#517]
When running a task via `EMRSparkOperator` (for example `core_client_count_view` or ` devtools_prerelease_events_to_amplitude`) you get a warning like this:

`[2019-05-26 01:35:53,442] {logging_mixin.py:95} WARNING - /usr/local/lib/python2.7/site-packages/airflow/models.py:1674: DeprecationWarning: BaseOperator.post_execute() now takes two arguments, `context` and `result`, but "core_client_count_view" only expected one. This behavior is deprecated and will be removed in a future version of Airflow.
  category=DeprecationWarning)`

Looks like we need to update the [`post_execute`](https://github.com/mozilla/telemetry-airflow/blob/a623a7c7542c54379732475f66d9284697ce96d3/dags/operators/emr_spark_operator.py#L59) method to take an additional argument.

**Comment by acmiyaguchi** [comment]
Deprecated in #1240
