### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by vitorbaptista** [mozilla/telemetry-airflow#61]
I've been looking for examples on how to use Airflow in practice and this repository is the best I've found. Thanks a lot!

I'm using this as the basis of a data pipeline for OpenTrials (https://github.com/opentrials/opentrials-airflow), as it's very well written and organised. As it's created by Mozilla and on GitHub, I'm assuming it's FLOSS. However, you don't specify a license, so I don't know under which terms. Could you add one?

Thanks again for the great work :clap:

**Comment by vitillo** [comment]
Glad you find this useful :) I have just added a FLOSS license to the project, thanks for bringing this up.
