### ISSUE TITLE
Create a "Wait for build" operator for dockerized components

### ISSUE THREAD

**Issue by fbertsch** [mozilla/telemetry-airflow#814]
Our general dockerized components arch looks like this:
1. GH repo has the code and associated docker build components
2. Circleci runs a build and deploy step on merge into master
3. Artifacts are deployed to Dockerhub or Google Container Registry

For jobs that run dockerized components, we often merge a change then rerun the job. However the build usually isn't deployed at that point. We should have an operator that checks for a build step and, if it's happening, waits for it before running the job.

**Comment by acmiyaguchi** [comment]
Is this an issue now? My understanding is that the kubernetes operator will always attempt to fetch the latest container, so there are no build time dependencies here. I'm going to close this unless there are strong opinions otherwise.
